# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/

# Setup
title:            Ian Sinnott
tagline:          "I make web apps, I travel. <br /> Sometimes I write about it."
masthead:         default.png
url:              http://blog.iansinnott.com
paginate:         8
baseurl:          /
author:
  name:           Ian Sinnott
  url:            https://www.iansinnott.com
  email:          ian@iansinnott.com

excerpt_separator: <!--more-->

image_dir: "/public/images/"

# Add Emoji support (only works on GitHub pages)
gems:
  - jemoji

# Custom vars
version:          0.1.0
github:
  repo:           https://github.com/iansinnott/iansinnott.github.io

# Excerpt length in words.
excerpt_length: 93
