# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            isinn
tagline:          A Blog by Ian Sinnott
url:              http://iansinnott.github.io
paginate:         5
baseurl:          /
author:
  name:           Ian Sinnott
  url:            http://iansinnott.com
  email:          ian@iansinnott.com

# Custom vars
version:          0.1.0
github:
  repo:           https://github.com/iansinnott/iansinnott.github.io
