# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            isinn
tagline:          A Blog by Ian Sinnott
url:              http://blog.iansinnott.com
paginate:         8
baseurl:          /
author:
  name:           Ian Sinnott
  url:            http://iansinnott.com
  email:          ian@iansinnott.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
