# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Ian Sinnott
tagline:          I write about stuff & things
url:              http://iansinnott.github.io
paginate:         8
baseurl:          /
author:
  name:           Ian Sinnott
  url:            http://iansinnott.com
  email:          ian@iansinnott.com

excerpt_separator: <!--more-->

# Custom vars
version:          0.1.0
github:
  repo:           https://github.com/iansinnott/iansinnott.github.io
